# Generated by Django 3.0.8 on 2020-07-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebHoundApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trace',
            name='id',
        ),
        migrations.AlterField(
            model_name='trace',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
