# Generated by Django 3.0.8 on 2020-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebHoundApp', '0002_auto_20200716_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='is_task_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trace',
            name='task_active_ts',
            field=models.DateTimeField(null=True),
        ),
    ]
