# Generated by Django 3.0.8 on 2020-07-22 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WebHoundApp', '0003_auto_20200721_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trace',
            name='is_task_active',
        ),
        migrations.AlterField(
            model_name='trace',
            name='task_active_ts',
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
