# Generated by Django 3.0.8 on 2020-07-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebHoundApp', '0004_auto_20200722_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
